import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Nav, Navbar, NavbarBrand, NavbarToggler, Collapse, NavItem, NavLink, NavbarText } from 'reactstrap';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <main className={styles.main}>
                <div>
                    <Navbar
                        color="light"
                        expand="md"
                        light
                    >
                        <NavbarBrand href="/">
      reactstrap
                        </NavbarBrand>
                        <NavbarToggler onClick={function noRefCheck() {}} />
                        <Collapse navbar>
                            <Nav
                                className="me-auto"
                                navbar
                            >
                                <NavItem>
                                    <NavLink href="/components/">
            Components
                                    </NavLink>
                                </NavItem>
                                <NavItem>
                                    <NavLink href="https://github.com/reactstrap/reactstrap">
            GitHub
                                    </NavLink>
                                </NavItem>
                            </Nav>
                            <NavbarText>
        Simple Text
                            </NavbarText>
                        </Collapse>
                    </Navbar>
                </div>

                <h1 className={styles.title}>
          OpexViewer
                </h1>

            </main>

            <footer className={styles.footer}>
                <a
                    href="https://t.me/pskucherov"
                    target="_blank"
                    rel="noopener noreferrer"
                >
          pskucherov
                </a>
            </footer>
        </div>
    );
}
